backend:
  name: github
  repo: nyakiochristine/lightforthecommunitywebsite  # Replace with your GitHub repo
  branch: main             # Your repo's default branch
  auth_type: implicit      # Use implicit grant flow for OAuth (recommended)
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: projects
    label: Projects
    folder: content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Summary, name: summary, widget: text}
      - {label: Body, name: body, widget: markdown}
